name: Deploy CloudFormation Stack

on:
  push:
    branches: [ main ]
    paths:
      - 'cloudformation/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod
      project_name:
        description: 'Project name'
        required: true
        default: 'myproject'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ github.event.inputs.project_name || 'myproject' }}-${{ github.event.inputs.environment || 'dev' }}-iam-stack
          template: cloudformation/iam-roles.yml
          parameter-overrides: >
            ProjectName=${{ github.event.inputs.project_name || 'myproject' }},
            Environment=${{ github.event.inputs.environment || 'dev' }}
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
